# Generated by Django 5.0 on 2023-12-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_origem', models.CharField(max_length=150)),
                ('agencia_origem', models.CharField(max_length=100)),
                ('conta_origem', models.CharField(max_length=100)),
                ('banco_destino', models.CharField(max_length=150)),
                ('agencia_destino', models.CharField(max_length=100)),
                ('conta_destino', models.CharField(max_length=100)),
                ('valor_transacao', models.FloatField()),
                ('data_transacao', models.DateField()),
            ],
        ),
    ]
